language: objective-c

branches:
  only:
    master

notifications:
  email: false

osx_image: xcode7.1
xcode_project: WoW-Realm-Tracker.xcodeproj
xcode_scheme: WoW-Realm-Tracker
xcode_sdk: iphonesimulator9.1
script: bin/test

cache:
  directories:
    - Carthage

before_install:
  - bin/install-carthage
  - bin/carthage-bootstrap-if-needed
  - bin/ci-setup
sudo: false
